#!/bin/sh

. /etc/control.d/functions-local-policy

CONFIG=/etc/openssh/sshd_config

new_subst users \
	'^[#[:space:]]*AllowGroups\s+wheel\s+users\s*$' \
	's/^\s*\(#\?\)[#[:space:]]*\(AllowGroups\)\s.*/\1\2 wheel users/'
new_subst remote \
	'^[#[:space:]]*AllowGroups\s+wheel\s+remote\s*$' \
	's/^\s*\(#\?\)[#[:space:]]*\(AllowGroups\)\s.*/\1\2 wheel remote/'
new_subst wheelonly \
	'^[#[:space:]]*AllowGroups\s+wheel\s*$' \
	's/^\s*\(#\?\)[#[:space:]]*\(AllowGroups\)\s.*/\1\2 wheel/'
new_subst remoteonly \
	'^[#[:space:]]*AllowGroups\s+remote\s*$' \
	's/^\s*\(#\?\)[#[:space:]]*\(AllowGroups\)\s.*/\1\2 remote/'

new_help users 'Allow SSH Access to groups wheel and users'
new_help remote 'Allow SSH Access to groups wheel and remote'
new_help wheelonly 'Allow SSH Access to group wheel only'
new_help remoteonly 'Allow SSH Access to group remote only'

new_summary 'OpenSSH server list of allowed groups configuration'

control_subst_with_file_check "$CONFIG" "$*" "users remote wheelonly remoteonly"
