#!/bin/sh

. /etc/control.d/functions-local-policy

CONFIG=/etc/openssh/sshd_config

new_subst enabled \
	'^\s*PermitEmptyPasswords\s+yes\s*$' \
	's/^[#[:space:]]*\(PermitEmptyPasswords\)\s\+.*/\1 yes/'

new_subst disabled \
	'^\s*PermitEmptyPasswords\s+no\s*$' \
	's/^[#[:space:]]*\(PermitEmptyPasswords\)\s\+.*/\1 no/'

new_subst default \
	'^\s*#[#[:space:]]*PermitEmptyPasswords\s.*' \
	's/^[#[:space:]]*\(PermitEmptyPasswords\)\s\+.*/#\1 no/'

new_help enabled 'Permit empty passwords'
new_help disabled 'Prohibit empty passwords'
new_help default 'Reset empty passwords setting to the package default (should be disabled)'

new_summary 'OpenSSH server PermitEmptyPasswords configuration'

control_subst_with_file_check "$CONFIG" "$*" "enabled disabled default"

